### ISSUE TITLE
report an error

### ISSUE THREAD

**Issue by hyqyoung** [lightaime/sgas#10]
when I run "python train_search.py --use_history --random_seed --data ./data", It reports  an error:
![image](https://user-images.githubusercontent.com/37873186/89990774-6df22b00-dcb5-11ea-9dc3-faddb0d5a0e0.png)

AttributeError: module 'torch_geometric.utils' has no attribute 'scatter_'

**Comment by lightaime** [comment]
Hi @hyqyoung. This seems to be one problem of your environment. Please ensure to install the required env following the instruction: https://github.com/lightaime/sgas/blob/master/sgas_env_install.sh

**Comment by hyqyoung** [comment]
> Hi @hyqyoung. This seems to be one problem of your environment. Please ensure to install the required env following the instruction: https://github.com/lightaime/sgas/blob/master/sgas_env_install.sh

I find the reason is using "pip install torch-geometric" will download the latest version of torch-geometric which is 1.6.1, 
but  the method "torch_geometric.utils.scatter_" only exists  before version 1.4.3 or earlier.
So I just update version 1.4.3 and it works. I also suggest you comment on this point.

**Comment by guochengqian** [comment]
@hyqyoung Hi. Thanks for letting us know. We will check the environment (may comment the pyg version on our sgas_env_install.sh, or consider support the latest version if it is necessary)
