### ISSUE TITLE
It seems that there is a bug about the pruned edges

### ISSUE THREAD

**Issue by linhaojia13** [lightaime/sgas#12]
https://github.com/lightaime/sgas/blob/6faff35c4c3f01a29e942d78357d9238c3b6faa6/gcn/gcn_point/model_search.py#L55-L64

Hi, @guochengqian 
In line 60, I think that 'continue' is more suitable rather than 'pass'. Using 'pass',  it will not skip line 63 and 'o_list' will additionally append the operator 'o' in last iteration. Do you think so?

**Comment by lightaime** [comment]
Hi @linhaojia13. You are right. It seems to be a bug added by mistake when we cleaned the code. The `o_list.append(o)` was inside the if-else statement in our original implementation. So the results should not be effected. Thanks for your suggestion. I replaced the 'pass' with  'continue'. Sorry for any inconvenience.

**Comment by linhaojia13** [comment]
It's my pleasure.
