### ISSUE TITLE
How “Sequential Greedy Architecture Search” impacts Kendall?

### ISSUE THREAD

**Issue by LiuFG** [lightaime/sgas#13]
It seems that "Sequential Greedy Architecture Search" is same with progressive method in P-DARTS. Have you measured how Greedy method impacts Kendall? Why not show all DARTS-based mehods' Kendall?

**Comment by lightaime** [comment]
Hi @LiuFG. In our paper, we show the impact of the proposed greedy method on Kendall comparing DARTS. It should be great to show it for other DARTS-based methods. But we didn't have enough time and machines to do it at the time of submission. Feel free to try it out on other DARTS-based mehods.
