### ISSUE TITLE
About the codes

### ISSUE THREAD

**Issue by 964918993** [lightaime/sgas#2]
Which deep learning framework did you use？ Tensorflow， Pytorch or any other one?
And when will you update your codes? 
Look forward to your reply.

**Comment by lightaime** [comment]
Hi, our implementation is based on Pytorch. We plan to release the whole code base. But since the paper is still under review, we are not sure about the exact date to release. Hopefully you can understand.

**Comment by 964918993** [comment]
Thank you for your reply.
I am a graduate student, and my research field is point cloud. I want to know if you can share the code with me alone. I promise it will only be used for academic research.

**Comment by 964918993** [comment]
Your research results are very good. I believe and hope your thesis will be employed soon.
I really hope you can share it with me, and I hope it won't disturb you.
And my address :964918993@qq.com.
Thanks!

**Comment by lightaime** [comment]
Great thanks to your interests. But this decision involved the concerns from authors' affliations. I can not release the codes regardless their suggestions. I will definately inform you when we have any updates on this.

**Comment by 964918993** [comment]
Thanks！
