### ISSUE TITLE
About the based code

### ISSUE THREAD

**Issue by 964918993** [lightaime/sgas#3]
Can you tell me whether the code is written by myself or modified based on which paper? If it is modified based on the existing code, can you tell me which paper's code is?
Thanks！

**Comment by lightaime** [comment]
Thanks for reaching out. The CNN search is based on DARTS [https://github.com/quark0/darts](https://github.com/quark0/darts). And the GCN part is based on the modules of DeepGCNs [https://github.com/lightaime/deep_gcns_torch](https://github.com/lightaime/deep_gcns_torch).

**Comment by lightaime** [comment]
We close this issue since the code is released.
