### ISSUE TITLE
Selection op

### ISSUE THREAD

**Issue by wuzhi19931128** [lightaime/sgas#4]
I think your idea is excellent and more naturally than those using sample such as SNAS. However , one problem of DARTS is the entropy  of  the operation distribution is very small. The maximum softmax value is about 0.3. So why the "Selection Certainty" can work? It's very common when the parameter of two  op is very close, the  "Selection Certainty" may be large because other op parameter is samll.
In this case  "Selection Certainty" may not work. And almost all edges suffer this problem, may increase difficulty .

**Comment by lightaime** [comment]
I am not sure if I understand for your question correctly. When the differences between ops are small, the entropy will be high (thus the Selection Certainty will be small). These edges are most likely to be decided in later epochs. And the ones with higher Selection Certainty will be decided earlier.

If you want to have a more stable result, you can also increase the decision interval `--decision_freq`. We found setting `--decision_freq 7` produced results with a lower variance.
