### ISSUE TITLE
out of memory (gcn)

### ISSUE THREAD

**Issue by visionman67** [lightaime/sgas#5]
Hi,
Nice work.
When training the searched model on ModelNet40 (using the provided command, and trained the model on one Tesla v100), the error occurs. What is the batchsize you used? And other parameters?
Thanks.

**Comment by lightaime** [comment]
Hi @visionman67 .
Did you use a Tesla V100 32G or a Tesla V100 16G? We used a Tesla V100 32G to train the large model.
If you suffer from Out of Memory (OOM) issue, you can train a compact model by runing:
`python main_modelnet.py --phase train --arch Cri2_ModelNet_Best --num_cells 3 --init_channels 128 --k 9 --save Cri2_modelnet40_best_l3_c128_k9` 
or reduce to batch size from 32 to 16 or even 8.

**Comment by visionman67** [comment]
Thanks for your quick reply. It indeed is 16G. Thanks for your advice so
much.
Best

Guohao Li <notifications@github.com> 于2020年5月11日周一 下午9:55写道：
